order = ["Introduction"]


[[classOrder]]
collapsed = false
classes = ["Dec", "VirtualInstance", "Root"]

[[classOrder]]
section = "Observables"
collapsed = false
classes = ["Observable", "State", "Record", "Dict", "Stopwatch", "Timer",
    "Alpha", "Eased", "Spring", "AngleSpring", "IntSpring"]

gitSourceBranch = "main"

[docusaurus]
url = "https://dec.ambergracesoftware.com"
baseUrl = "/"
tagline = "A Library for Building Roblox User Interfaces"

[navbar]
title = ""

[navbar.logo]
alt = "Dec"
src = "logo.svg"

[home]
enabled = true
includeReadme = false

[footer]
copyright = "Written by Amber Grace. Built with Moonwave and Docusaurus"