[package]
name = "ambergracesoftware/dex"
description = "A library for building reactive user interfaces on Roblox"
version = "0.1.7"
authors = [ "Amber Grace" ]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["aftman.toml", "default.project.json"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"