[package]
name = "ambergracesoftware/dec"
description = "A libary for building Roblox user interfaces"
version = "0.1.1"
authors = [ "Amber Grace" ]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["aftman.toml", "default.project.json"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"