name: Publish Wally Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Generate minimal project structure
        run: |
          mkdir temp
          cp -r src temp
          cp wally.toml temp/src
          cp aftman.toml temp/src
          cp README.md temp/src
          cp LICENSE temp/src
          cd temp/src
      - name: Setup aftman toolchain
        uses: ok-nick/setup-aftman@v0.3.0
      - name: Push Release to Wally
        env:
          WALLY_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wally publish --token $WALLY_AUTH_TOKEN